apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-node-dns
  namespace: kube-system
  labels:
    k8s-app: kube-node-dns
spec:
  selector:
    matchLabels:
      k8s-app: kube-node-dns
  template:
    metadata:
      labels:
        k8s-app: kube-node-dns
    spec:
      serviceAccountName: kube-node-dns
      containers:
        - name: kube-node-dns
          image: basefly/kube-node-dns
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - ./kube-node-dns
          args:
            - --configmap_name=dns-node
          resources:
            limits:
              memory: 500Mi
              cpu: 200m
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - hostPath:
            path: /etc/localtime
            type: File
          name: localtime
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-node-dns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-node-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-node-dns
subjects:
  - kind: ServiceAccount
    name: kube-node-dns
    namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-node-dns
  namespace: kube-system
rules:
  - apiGroups: ["core"]
    resources: ["configmaps"]
    verbs: ["*"]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "list","watch"]
