apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-node-dns-cm
  namespace: kube-system
  labels:
    k8s-app: kube-node-dns-cm
spec:
  selector:
    matchLabels:
      k8s-app: kube-node-dns-cm
  template:
    metadata:
      labels:
        k8s-app: kube-node-dns-cm
    spec:
      serviceAccountName: kube-node-dns
      containers:
        - name: kube-node-dns-cm
          image: basefly/kube-node-dns
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - ./kube-node-dns
          args:
            - --configmap_name=dns-node
          resources:
            limits:
              memory: 500Mi
              cpu: 200m
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
      volumes:
        - hostPath:
            path: /etc/localtime
            type: File
          name: localtime
---
