apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-node-dns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-node-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-node-dns
subjects:
  - kind: ServiceAccount
    name: kube-node-dns
    namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-node-dns
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "list","watch"]
